#!/bin/bash

alias ll="ls -lha"

# GIT extension
if [ -f /usr/bin/git ];then
    alias __git_ps1="git branch 2>/dev/null | grep '*' | sed 's/* \(.*\)/(\1)/'"
    export PS1="\[\033[93m\]\u\[\033[32m\]@\h\[\033[1;34m\]\$(__git_ps1)\[\033[37m\]:\w$ "
else
    export PS1="\[\033[93m\]\u\[\033[32m\]@\h:\[\033[37m\]\w$ "
fi
